// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module addr_table_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 6
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output addr_table_reg_pkg::addr_table_reg2hw_t reg2hw, // Write


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import addr_table_reg_pkg::* ;

  localparam int DW = 64;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [63:0] data_0_qs;
  logic [63:0] data_0_wd;
  logic data_0_we;
  logic [63:0] data_1_qs;
  logic [63:0] data_1_wd;
  logic data_1_we;
  logic [63:0] data_2_qs;
  logic [63:0] data_2_wd;
  logic data_2_we;
  logic [63:0] data_3_qs;
  logic [63:0] data_3_wd;
  logic data_3_we;
  logic valid_valid_0_qs;
  logic valid_valid_0_wd;
  logic valid_valid_0_we;
  logic valid_valid_1_qs;
  logic valid_valid_1_wd;
  logic valid_valid_1_we;
  logic valid_valid_2_qs;
  logic valid_valid_2_wd;
  logic valid_valid_2_we;
  logic valid_valid_3_qs;
  logic valid_valid_3_wd;
  logic valid_valid_3_we;
  logic start_qs;
  logic start_wd;
  logic start_we;

  // Register instances

  // Subregister 0 of Multireg data
  // R[data_0]: V(False)

  prim_subreg #(
    .DW      (64),
    .SWACCESS("RW"),
    .RESVAL  (64'h0)
  ) u_data_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data_0_we),
    .wd     (data_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[0].q ),

    // to register interface (read)
    .qs     (data_0_qs)
  );

  // Subregister 1 of Multireg data
  // R[data_1]: V(False)

  prim_subreg #(
    .DW      (64),
    .SWACCESS("RW"),
    .RESVAL  (64'h0)
  ) u_data_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data_1_we),
    .wd     (data_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[1].q ),

    // to register interface (read)
    .qs     (data_1_qs)
  );

  // Subregister 2 of Multireg data
  // R[data_2]: V(False)

  prim_subreg #(
    .DW      (64),
    .SWACCESS("RW"),
    .RESVAL  (64'h0)
  ) u_data_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data_2_we),
    .wd     (data_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[2].q ),

    // to register interface (read)
    .qs     (data_2_qs)
  );

  // Subregister 3 of Multireg data
  // R[data_3]: V(False)

  prim_subreg #(
    .DW      (64),
    .SWACCESS("RW"),
    .RESVAL  (64'h0)
  ) u_data_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data_3_we),
    .wd     (data_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[3].q ),

    // to register interface (read)
    .qs     (data_3_qs)
  );



  // Subregister 0 of Multireg valid
  // R[valid]: V(False)

  // F[valid_0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_valid_valid_0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (valid_valid_0_we),
    .wd     (valid_valid_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.valid[0].q ),

    // to register interface (read)
    .qs     (valid_valid_0_qs)
  );


  // F[valid_1]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_valid_valid_1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (valid_valid_1_we),
    .wd     (valid_valid_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.valid[1].q ),

    // to register interface (read)
    .qs     (valid_valid_1_qs)
  );


  // F[valid_2]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_valid_valid_2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (valid_valid_2_we),
    .wd     (valid_valid_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.valid[2].q ),

    // to register interface (read)
    .qs     (valid_valid_2_qs)
  );


  // F[valid_3]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_valid_valid_3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (valid_valid_3_we),
    .wd     (valid_valid_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.valid[3].q ),

    // to register interface (read)
    .qs     (valid_valid_3_qs)
  );



  // R[start]: V(False)

  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_start (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (start_we),
    .wd     (start_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.start.q ),

    // to register interface (read)
    .qs     (start_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == ADDR_TABLE_DATA_0_OFFSET);
    addr_hit[1] = (reg_addr == ADDR_TABLE_DATA_1_OFFSET);
    addr_hit[2] = (reg_addr == ADDR_TABLE_DATA_2_OFFSET);
    addr_hit[3] = (reg_addr == ADDR_TABLE_DATA_3_OFFSET);
    addr_hit[4] = (reg_addr == ADDR_TABLE_VALID_OFFSET);
    addr_hit[5] = (reg_addr == ADDR_TABLE_START_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(ADDR_TABLE_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(ADDR_TABLE_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(ADDR_TABLE_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(ADDR_TABLE_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(ADDR_TABLE_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(ADDR_TABLE_PERMIT[5] & ~reg_be)))));
  end

  assign data_0_we = addr_hit[0] & reg_we & !reg_error;
  assign data_0_wd = reg_wdata[63:0];

  assign data_1_we = addr_hit[1] & reg_we & !reg_error;
  assign data_1_wd = reg_wdata[63:0];

  assign data_2_we = addr_hit[2] & reg_we & !reg_error;
  assign data_2_wd = reg_wdata[63:0];

  assign data_3_we = addr_hit[3] & reg_we & !reg_error;
  assign data_3_wd = reg_wdata[63:0];

  assign valid_valid_0_we = addr_hit[4] & reg_we & !reg_error;
  assign valid_valid_0_wd = reg_wdata[0];

  assign valid_valid_1_we = addr_hit[4] & reg_we & !reg_error;
  assign valid_valid_1_wd = reg_wdata[1];

  assign valid_valid_2_we = addr_hit[4] & reg_we & !reg_error;
  assign valid_valid_2_wd = reg_wdata[2];

  assign valid_valid_3_we = addr_hit[4] & reg_we & !reg_error;
  assign valid_valid_3_wd = reg_wdata[3];

  assign start_we = addr_hit[5] & reg_we & !reg_error;
  assign start_wd = reg_wdata[0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[63:0] = data_0_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[63:0] = data_1_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[63:0] = data_2_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[63:0] = data_3_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[0] = valid_valid_0_qs;
        reg_rdata_next[1] = valid_valid_1_qs;
        reg_rdata_next[2] = valid_valid_2_qs;
        reg_rdata_next[3] = valid_valid_3_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[0] = start_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module addr_table_reg_top_intf
#(
  parameter int AW = 6,
  localparam int DW = 64
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output addr_table_reg_pkg::addr_table_reg2hw_t reg2hw, // Write
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  addr_table_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .devmode_i
  );
  
endmodule


