// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package addr_table_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 6;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [63:0] q;
  } addr_table_reg2hw_data_mreg_t;

  typedef struct packed {
    logic        q;
  } addr_table_reg2hw_valid_mreg_t;

  typedef struct packed {
    logic        q;
  } addr_table_reg2hw_start_reg_t;

  // Register -> HW type
  typedef struct packed {
    addr_table_reg2hw_data_mreg_t [3:0] data; // [260:5]
    addr_table_reg2hw_valid_mreg_t [3:0] valid; // [4:1]
    addr_table_reg2hw_start_reg_t start; // [0:0]
  } addr_table_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ADDR_TABLE_DATA_0_OFFSET = 6'h 0;
  parameter logic [BlockAw-1:0] ADDR_TABLE_DATA_1_OFFSET = 6'h 8;
  parameter logic [BlockAw-1:0] ADDR_TABLE_DATA_2_OFFSET = 6'h 10;
  parameter logic [BlockAw-1:0] ADDR_TABLE_DATA_3_OFFSET = 6'h 18;
  parameter logic [BlockAw-1:0] ADDR_TABLE_VALID_OFFSET = 6'h 20;
  parameter logic [BlockAw-1:0] ADDR_TABLE_START_OFFSET = 6'h 28;

  // Register index
  typedef enum int {
    ADDR_TABLE_DATA_0,
    ADDR_TABLE_DATA_1,
    ADDR_TABLE_DATA_2,
    ADDR_TABLE_DATA_3,
    ADDR_TABLE_VALID,
    ADDR_TABLE_START
  } addr_table_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ADDR_TABLE_PERMIT [6] = '{
    4'b 1111, // index[0] ADDR_TABLE_DATA_0
    4'b 1111, // index[1] ADDR_TABLE_DATA_1
    4'b 1111, // index[2] ADDR_TABLE_DATA_2
    4'b 1111, // index[3] ADDR_TABLE_DATA_3
    4'b 0001, // index[4] ADDR_TABLE_VALID
    4'b 0001  // index[5] ADDR_TABLE_START
  };

endpackage

